language: node_js
node_js:
  - 0.12
notifications:
  email:
    recipients:
      - liban.moh99@gmail.com
      - 2406722891@vtext.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
